"""
Axiom Zero - IR to Lean 4 Compiler
Translates normalized IR into Lean 4 skeleton code with proof holes.
"""

from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field

from ast_extractor.ir import (
    NormalizedIR,
    FunctionIR,
    ClassIR,
    LoopIR,
    ConditionalIR,
    StatementIR,
    ExpressionIR,
    TypeAnnotationIR,
    TypeKind,
)


@dataclass
class LeanSkeleton:
    """
    Generated Lean 4 code skeleton.
    Contains complete code with sorry holes for proofs.
    """
    imports: List[str] = field(default_factory=list)
    declarations: List[str] = field(default_factory=list)
    proof_holes: List[Dict[str, Any]] = field(default_factory=list)

    # Statistics
    total_functions: int = 0
    total_holes: int = 0
    simple_holes: int = 0  # Can be solved by simp/omega
    complex_holes: int = 0  # Need MCTS

    def add_import(self, import_name: str):
        """Add import statement."""
        if import_name not in self.imports:
            self.imports.append(import_name)

    def add_declaration(self, decl: str):
        """Add Lean declaration."""
        self.declarations.append(decl)

    def add_hole(self, hole: Dict[str, Any]):
        """Add proof hole."""
        self.proof_holes.append(hole)
        self.total_holes += 1

        # Classify hole complexity
        if hole.get('complexity') == 'simple':
            self.simple_holes += 1
        else:
            self.complex_holes += 1

    def to_string(self) -> str:
        """Convert to Lean 4 code string."""
        lines = []

        # Add imports
        lines.append("-- Auto-generated by Axiom Zero")
        lines.append("")
        for imp in self.imports:
            lines.append(f"import {imp}")
        lines.append("")
        lines.append("open Classical")
        lines.append("open Nat")
        lines.append("")

        # Add declarations
        for decl in self.declarations:
            lines.append(decl)
            lines.append("")

        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'imports': self.imports,
            'declarations': self.declarations,
            'proof_holes': self.proof_holes,
            'statistics': {
                'total_functions': self.total_functions,
                'total_holes': self.total_holes,
                'simple_holes': self.simple_holes,
                'complex_holes': self.complex_holes
            }
        }


class IRtoLeanCompiler:
    """
    Compiles normalized IR to Lean 4 skeleton code.
    Generates complete code with sorry holes for proof obligations.
    """

    def __init__(self):
        """Initialize compiler."""
        self.skeleton = LeanSkeleton()
        self.hole_counter = 0

    def compile(self, ir: NormalizedIR) -> LeanSkeleton:
        """
        Compile normalized IR to Lean 4 skeleton.

        Args:
            ir: Normalized IR from AST extraction

        Returns:
            LeanSkeleton with generated code and proof holes
        """
        self.skeleton = LeanSkeleton()
        self.hole_counter = 0

        # Add required imports
        self._add_standard_imports(ir)

        # Compile classes
        for cls in ir.classes:
            self._compile_class(cls)

        # Compile functions
        for func in ir.functions:
            self._compile_function(func)

        # Update statistics
        self.skeleton.total_functions = len(
            ir.functions) + sum(len(cls.methods) for cls in ir.classes)

        return self.skeleton

    def _add_standard_imports(self, ir: NormalizedIR):
        """Add standard Mathlib imports based on IR content."""
        # Always import these
        self.skeleton.add_import("Mathlib.Data.Nat.Basic")
        self.skeleton.add_import("Mathlib.Data.List.Basic")

        # Check for tensor operations
        has_tensors = any(
            func.tensor_operations
            for func in ir.functions
        )
        if has_tensors:
            self.skeleton.add_import("Mathlib.Data.Matrix.Basic")
            self.skeleton.add_import("Mathlib.LinearAlgebra.Matrix.Notation")

        # Check for specific operations
        for func in ir.functions:
            for stmt in func.body:
                if isinstance(stmt, LoopIR):
                    self.skeleton.add_import("Mathlib.Tactic.Linarith")
                if isinstance(stmt, ConditionalIR):
                    self.skeleton.add_import("Mathlib.Tactic.SplitIfs")

    def _compile_class(self, cls: ClassIR):
        """Compile class definition."""
        lines = [f"-- Class: {cls.name}"]

        # Class structure as namespace
        lines.append(f"namespace {cls.name}")
        lines.append("")

        # Compile methods
        for method in cls.methods:
            method_code = self._compile_function_to_string(
                method, is_method=True)
            lines.append(method_code)
            lines.append("")

        lines.append(f"end {cls.name}")

        self.skeleton.add_declaration("\n".join(lines))

    def _compile_function(self, func: FunctionIR):
        """Compile function definition."""
        func_code = self._compile_function_to_string(func)
        self.skeleton.add_declaration(func_code)

    def _compile_function_to_string(self, func: FunctionIR,
                                    is_method: bool = False) -> str:
        """
        Compile function to Lean 4 code string.

        Args:
            func: FunctionIR to compile
            is_method: Whether this is a class method

        Returns:
            Lean 4 function code
        """
        lines = []

        # Function signature
        sig = func.signature
        params_str = self._compile_parameters(sig.parameters)
        return_type_str = self._compile_type(
            sig.return_type) if sig.return_type else "Unit"

        func_name = sig.name
        if is_method:
            func_name = func_name.removeprefix("__").removeprefix("_")

        lines.append(f"def {func_name} ({params_str}) : {return_type_str} :=")

        # Function body
        if func.body:
            body_code = self._compile_body(func.body, indent=2)
            lines.append(body_code)
        else:
            # Empty function - add sorry
            hole_id = self._create_hole(
                description="Empty function body",
                func_name=func_name,
                complexity="simple"
            )
            lines.append(f"  sorry  -- hole_{hole_id}")

        return "\n".join(lines)

    def _compile_parameters(self, parameters: List[Dict]) -> str:
        """Compile function parameters."""
        param_strs = []
        for param in parameters:
            name = param['name']
            type_str = self._compile_type(
                param.get('type')) if param.get('type') else "α"
            param_strs.append(f"{name} : {type_str}")

        return " ".join(param_strs)

    def _compile_type(self, type_ann: Optional[TypeAnnotationIR]) -> str:
        """Compile type annotation to Lean 4 type."""
        if type_ann is None:
            return "α"

        if type_ann.type_kind == TypeKind.INT:
            return "ℕ"
        elif type_ann.type_kind == TypeKind.FLOAT:
            return "ℝ"
        elif type_ann.type_kind == TypeKind.BOOL:
            return "Bool"
        elif type_ann.type_kind == TypeKind.STRING:
            return "String"
        elif type_ann.type_kind == TypeKind.TENSOR:
            # Tensor as matrix
            if type_ann.shape:
                dims = " × ".join(
                    [str(d) if d > 0 else "n" for d in type_ann.shape])
                return f"Matrix ({dims})"
            return "Matrix"
        elif type_ann.type_kind == TypeKind.LIST:
            if type_ann.element_type:
                elem_type = self._compile_type(type_ann.element_type)
                return f"List {elem_type}"
            return "List α"
        elif type_ann.type_kind == TypeKind.DICT:
            return "Map"
        elif type_ann.type_kind == TypeKind.VOID:
            return "Unit"
        else:
            return "α"

    def _compile_body(self, body: List, indent: int = 2) -> str:
        """Compile function body."""
        lines = []
        indent_str = "  " * indent

        for i, node in enumerate(body):
            if isinstance(node, StatementIR):
                line = self._compile_statement(node, indent)
                if line:
                    lines.append(line)
            elif isinstance(node, LoopIR):
                loop_code = self._compile_loop(node, indent)
                lines.append(loop_code)
            elif isinstance(node, ConditionalIR):
                cond_code = self._compile_conditional(node, indent)
                lines.append(cond_code)

        # If no statements, return sorry
        if not lines:
            hole_id = self._create_hole(
                description="Empty block",
                complexity="simple"
            )
            return f"{indent_str}sorry  -- hole_{hole_id}"

        # Wrap in by block if multiple statements
        if len(lines) > 1:
            result = [f"{indent_str}by"]
            for line in lines:
                result.append(f"  {line}")
            return "\n".join(result)
        else:
            return lines[0]

    def _compile_statement(self, stmt: StatementIR, indent: int) -> str:
        """Compile statement to Lean 4."""
        indent_str = "  " * indent

        if stmt.stmt_type == 'assignment':
            if stmt.expression:
                expr_str = self._compile_expression(stmt.expression)
                return f"{indent_str}let {stmt.target} := {expr_str}"
            else:
                return f"{indent_str}let {stmt.target} : α := sorry"

        elif stmt.stmt_type == 'return':
            if stmt.expression:
                expr_str = self._compile_expression(stmt.expression)
                return f"{indent_str}exact {expr_str}"
            else:
                return f"{indent_str}exact ()"

        elif stmt.stmt_type == 'expression':
            if stmt.expression:
                expr_str = self._compile_expression(stmt.expression)
                # Check if it's a tensor operation
                if stmt.expression.is_tensor_operation():
                    hole_id = self._create_hole(
                        description=f"Tensor operation: {stmt.expression.function_name}",
                        complexity="complex"
                    )
                    return f"{indent_str}sorry  -- hole_{hole_id}: {expr_str}"
                return f"{indent_str}{expr_str}"

        elif stmt.stmt_type == 'pass':
            return f"{indent_str}skip"

        return f"{indent_str}sorry  -- unimplemented statement"

    def _compile_loop(self, loop: LoopIR, indent: int) -> str:
        """Compile loop to Lean 4."""
        indent_str = "  " * indent

        if loop.loop_type == 'for' and loop.range_start is not None:
            # Bounded for loop - compile to recursion or induction
            start = self._compile_expression(loop.range_start)
            end = self._compile_expression(loop.range_end)

            # Add loop invariant as forall statement
            invariant_str = self._generate_loop_invariant(loop, indent)

            lines = [
                f"{indent_str}-- Loop invariant: {invariant_str}",
                f"{indent_str}have h_loop : ∀ i, {start} ≤ i ∧ i < {end} → P i := by",
                f"{indent_str}  sorry  -- hole_{self._create_hole(description='loop invariant', complexity='complex')}",
                f"{indent_str}exact h_loop ..."
            ]

            return "\n".join(lines)

        elif loop.loop_type == 'for':
            # General for loop
            iter_str = self._compile_expression(
                loop.iterable) if loop.iterable else "list"

            lines = [
                f"{indent_str}-- For loop over {iter_str}",
                f"{indent_str}have h_for : ∀ x ∈ {iter_str}, P x := by",
                f"{indent_str}  sorry  -- hole_{self._create_hole(description='for loop', complexity='complex')}",
                f"{indent_str}exact h_for ..."
            ]

            return "\n".join(lines)

        elif loop.loop_type == 'while':
            cond_str = self._compile_expression(
                loop.condition) if loop.condition else "True"

            lines = [
                f"{indent_str}-- While loop with condition: {cond_str}",
                f"{indent_str}have h_while : While {cond_str} := by",
                f"{indent_str}  sorry  -- hole_{self._create_hole(description='while loop', complexity='complex')}",
                f"{indent_str}exact h_while"
            ]

            return "\n".join(lines)

        return f"{indent_str}sorry  -- unimplemented loop"

    def _compile_conditional(self, cond: ConditionalIR, indent: int) -> str:
        """Compile conditional to Lean 4."""
        indent_str = "  " * indent
        cond_str = self._compile_expression(cond.condition)

        lines = [
            f"{indent_str}if h : {cond_str} then",
        ]

        # Then branch
        if cond.then_branch:
            then_code = self._compile_body(cond.then_branch, indent + 1)
            lines.append(then_code)
        else:
            lines.append(
                f"{indent_str}  sorry  -- hole_{self._create_hole(description='if branch', complexity='simple')}")

        lines.append(f"{indent_str}else")

        # Else branch
        if cond.else_branch:
            else_code = self._compile_body(cond.else_branch, indent + 1)
            lines.append(else_code)
        else:
            lines.append(
                f"{indent_str}  sorry  -- hole_{self._create_hole(description='else branch', complexity='simple')}")

        return "\n".join(lines)

    def _compile_expression(self, expr: ExpressionIR) -> str:
        """Compile expression to Lean 4."""
        if expr.expr_type == 'literal':
            if isinstance(expr.value, bool):
                return str(expr.value).lower()
            elif isinstance(expr.value, (int, float)):
                return str(expr.value)
            elif isinstance(expr.value, str):
                return f'"{expr.value}"'
            return str(expr.value)

        elif expr.expr_type == 'variable':
            return expr.value

        elif expr.expr_type == 'binary_op':
            left = self._compile_expression(expr.left) if expr.left else "?"
            right = self._compile_expression(expr.right) if expr.right else "?"

            # Map operators
            op_map = {
                '+': '+',
                '-': '-',
                '*': '*',
                '/': '/',
                '==': '=',
                '!=': '!=',
                '<': '<',
                '<=': '<=',
                '>': '>',
                '>=': '>=',
                'and': 'and',
                'or': 'or',
            }

            op = op_map.get(expr.operator, expr.operator)
            return f"{left} {op} {right}"

        elif expr.expr_type == 'call':
            func_name = expr.function_name or "unknown"
            args = ", ".join([self._compile_expression(arg)
                             for arg in expr.arguments])
            return f"{func_name} {args}"

        elif expr.expr_type == 'attribute':
            return ".".join(expr.attributes)

        elif expr.expr_type == 'subscript':
            base = self._compile_expression(expr.left) if expr.left else "?"
            idx = self._compile_expression(expr.right) if expr.right else "?"
            return f"{base}[{idx}]"

        return "?"

    def _generate_loop_invariant(self, loop: LoopIR, indent: int) -> str:
        """Generate loop invariant as forall statement."""
        var = loop.variable or "i"

        if loop.range_start and loop.range_end:
            start = self._compile_expression(loop.range_start)
            end = self._compile_expression(loop.range_end)
            return f"∀ {var}, {start} ≤ {var} ∧ {var} < {end} → P({var})"

        return f"∀ {var}, P({var})"

    def _create_hole(self, description: str = "unknown",
                     func_name: str = None,
                     complexity: str = "complex") -> int:
        """
        Create a proof hole.

        Args:
            func_name: Associated function name
            description: Description of what needs to be proved
            complexity: 'simple' or 'complex'

        Returns:
            Hole ID
        """
        hole_id = self.hole_counter
        self.hole_counter += 1

        hole = {
            'id': hole_id,
            'function': func_name,
            'description': description,
            'complexity': complexity,
            'suggested_tactic': 'simp' if complexity == 'simple' else 'mcts'
        }

        self.skeleton.add_hole(hole)

        return hole_id

    def compile_to_file(self, ir: NormalizedIR, output_path: str):
        """
        Compile IR and write to file.

        Args:
            ir: Normalized IR
            output_path: Output file path
        """
        skeleton = self.compile(ir)

        with open(output_path, 'w') as f:
            f.write(skeleton.to_string())

        return skeleton
